# SignReferences appveyor.yml script

branches:
  only:
    - master

version: '{branch}-{build}'
	
os: Visual Studio 2015
install:
  - set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%

before_build:
  nuget restore

configuration: Release
platform: Any CPU

build:
  parallel: true
  publish_nuget: false
  publish_nuget_symbols: false
  verbosity: minimal

artifacts:
  - path: 'SignReferences\bin\$(configuration)\*.nupkg'

deploy:
  provider: NuGet
  api_key:
    secure: rEYnR9JThbc6x8DdCo1K8+fgsGKzjNKzTZsldXFLYMm/tFPC7JWWvuKpVTrDBd+g
  skip_symbols: false

after_test:
  ps: Get-ChildItem .\*.nupkg | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
